Debug: false
Setting:
  DisableEntityVehicleEnter: true
  DisableBoneMeal: true
  MendingEnchantChance: 0.01
  DisableBedExplode: true
  DeathPenalty:
    Enabled: true
    SpawnLocation: ''
  PlayerTaskTick: 20
  #VillageTrade:
  #  DisableEnchant:
  #    Enabled: true
  #    List:
  #      - mending