Debug: false
Setting:
  BackupTicks: 36000
  DisableEntityVehicleEnter: true
  DisableBoneMeal: true
  MendingEnchantChance: 0.01
  DisableBedExplode: true
  DisableTrade: true
  OneShotProtection:
    Enabled: true
    Health: 0.95
    NoDamageTicks: 30
    CoolDown: 5
  CustomHealthRegen:
    DisableVanillaRegen: true
    BaseRegen: 1.5
    Seconds: 3
    MinFoodLevel: 6
  DeathPenalty:
    Enabled: true
    BalancePercent: 0.5
    RemoveChanceForSlot: 0.75
    WorldList:
      world:
        - DISABLED
      world_nether:
        - CHEST
        - INVENTORY
        - BALANCE
      world_the_end:
        - DISABLED
      iris_world:
        - CHEST
        - INVENTORY
        - BALANCE
  PlayerTaskTick: 20
  ShieldCooldownTick: 30
  CombatSeconds: 10
  BreedChance: 0.15
  ReduceArrowDamage: 0.5
  WorldName:
    world: "#00f1ff[메인월드]"
    world_nether: "#d32a00[지옥]"
    world_the_end: "#ff1af9[엔더]"
  ExtraEnchantItemDamage:
    Mending: 5
    Infinity: 5
    Fortune: 5
  ChangeWorldMessage:
    world_nether: "&c네더는 매우 위험한 장소입니다. 충분한 준비를 한 후 도전해주세요"
  DisableUse:
    Enabled: true
    RightClick:
      - chest_minecart
      - oak_chest_boat
      - bamboo_chest_raft
      - spruce_chest_boat
      - birch_chest_boat
      - jungle_chest_boat
      - acacia_chest_boat
      - dark_oak_chest_boat
      - mangrove_chest_boat
      - cherry_chest_boat
      - hopper_minecart
      - tnt
      - observer
      - tnt_minecart
      - beacon
      - hopper
      - dispenser
      - dropper
      - Grindstone
    ShiftRightClick:
      - chest_minecart
      - oak_chest_boat
      - bamboo_chest_raft
      - spruce_chest_boat
      - birch_chest_boat
      - jungle_chest_boat
      - acacia_chest_boat
      - dark_oak_chest_boat
      - mangrove_chest_boat
      - cherry_chest_boat
      - hopper_minecart
      - tnt
      - observer
      - tnt_minecart
      - beacon
      - hopper
      - dispenser
      - dropper
      - Grindstone
    LeftClick: []
    ShiftLeftClick: []
  OreDisguise: # Use MythicMobs
    Enabled: true
    List:
      COAL_ORE:
        InternalName: "Disguise_CoalOre"
        Chance: 0.05
      DEEPSLATE_COAL_ORE:
        InternalName: "Disguise_DeepslateCoalOre"
        Chance: 0.05
      IRON_ORE:
        InternalName: "Disguise_IronOre"
        Chance: 0.05
      DEEPSLATE_IRON_ORE:
        InternalName: "Disguise_DeepslateIronOre"
        Chance: 0.05
      COPPER_ORE:
        InternalName: "Disguise_CopperOre"
        Chance: 0.05
      DEEPSLATE_COPPER_ORE:
        InternalName: "Disguise_DeepslateCopperOre"
        Chance: 0.05
      GOLD_ORE:
        InternalName: "Disguise_GoldOre"
        Chance: 0.05
      DEEPSLATE_GOLD_ORE:
        InternalName: "Disguise_DeepslateGoldOre"
        Chance: 0.05
      REDSTONE_ORE:
        InternalName: "Disguise_RedStoneOre"
        Chance: 0.05
      DEEPSLATE_REDSTONE_ORE:
        InternalName: "Disguise_DeepslateRedStoneOre"
        Chance: 0.05
      EMERALD_ORE:
        InternalName: "Disguise_EmeraldOre"
        Chance: 0.05
      DEEPSLATE_EMERALD_ORE:
        InternalName: "Disguise_DeepslateEmeraldOre"
        Chance: 0.05
      LAPIS_ORE:
        InternalName: "Disguise_LapisOre"
        Chance: 0.05
      DEEPSLATE_LAPIS_ORE:
        InternalName: "Disguise_DeepslateLapisOre"
        Chance: 0.05
      DIAMOND_ORE:
        InternalName: "Disguise_DiamondOre"
        Chance: 0.05
      DEEPSLATE_DIAMOND_ORE:
        InternalName: "Disguise_DeepslateDiamondOre"
        Chance: 0.05
      NETHER_GOLD_ORE:
        InternalName: "Disguise_NetherGoldOre"
        Chance: 0.05
Streamer:
  BaseInvitePrice: 150000
  PerInvitePrice: 20000
  RegionProtectRadius: 150
  MaxInviteCount: 10
  RegionPaySeconds: 86400
  PrefixChangePrice: 50000
  RegionWorld:
    - iris_world
  RegionPrice:
    '1': 0
    '2': 10000
    '3': 20000
    '4': 40000
    '5': 70000
    '6': 100000
    '7': 140000
    '8': 190000
    '9': 250000
    '10': 320000
  ShopPenalty:
    '1': 0.05
    '2': 0.1
    '3': 0.15
    '4': 0.2
    '5': 0.25
    '6': 0.3
    '7': 0.35
    '8': 0.4
    '9': 0.45
    '10': 0.5
  List: