name: HardcoreSurvival
version: "1.0" #'${project.version}'
main: me.msicraft.hardcoresurvival.HardcoreSurvival
api-version: '1.21'
depend: [Vault]
commands:
  hardcoresurvival:
    description: 'Main commands'
